### ISSUE TITLE
TypeError: Cannot read property 'level' of null, in BattlePVP

### ISSUE THREAD

**Issue by sidawson** [IdleLands/IdleLands#137]
TypeError: Cannot read property 'level' of null
    at /Users/si/Code/git/meIdle/src/plugins/events/events/BattlePvP.js:44:22
    at /Users/si/Code/git/meIdle/node_modules/lodash/lodash.js:10281:37
    at arrayFilter (/Users/si/Code/git/meIdle/node_modules/lodash/lodash.js:588:11)
    at Function.reject (/Users/si/Code/git/meIdle/node_modules/lodash/lodash.js:9422:14)
    at interceptor (/Users/si/Code/git/meIdle/node_modules/lodash/lodash.js:16619:35)
    at thru (/Users/si/Code/git/meIdle/node_modules/lodash/lodash.js:8459:14)
    at /Users/si/Code/git/meIdle/node_modules/lodash/lodash.js:4216:28
    at arrayReduce (/Users/si/Code/git/meIdle/node_modules/lodash/lodash.js:689:21)
    at baseWrapperValue (/Users/si/Code/git/meIdle/node_modules/lodash/lodash.js:4215:14)
    at LazyWrapper.lazyValue [as value] (/Users/si/Code/git/meIdle/node_modules/lodash/lodash.js:1835:16)
    at baseWrapperValue (/Users/si/Code/git/meIdle/node_modules/lodash/lodash.js:4213:25)
    at LodashWrapper.wrapperValue (/Users/si/Code/git/meIdle/node_modules/lodash/lodash.js:8715:14)
    at LodashWrapper.object.(anonymous function) [as sample] (/Users/si/Code/git/meIdle/node_modules/lodash/lodash.js:15341:55)
    at Function.operateOn (/Users/si/Code/git/meIdle/src/plugins/events/events/BattlePvP.js:48:10)
    at Function.tryToDoEvent (/Users/si/Code/git/meIdle/src/plugins/events/eventhandler.js:41:17)
    at Player.takeTurn (/Users/si/Code/git/meIdle/src/plugins/players/player.js:93:18)

this is happening VERY often, when running in battle test mode, with 100 users.

**Comment by seiyria** [comment]
fixed in an upcoming commit
