### ISSUE TITLE
giving an item while not having a pet is broken

### ISSUE THREAD

**Issue by seiyria** [IdleLands/IdleLands#304]
```
Sep 22 11:43:51 idlelands app/web.1:  TypeError: Cannot read property '$pets' of undefined 
Sep 22 11:43:51 idlelands app/web.1:      at _callee$ (/app/dist/plugins/pets/pet.player.giveitem.socket.js:44:25) 
Sep 22 11:43:51 idlelands app/web.1:      at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:62:40) 
Sep 22 11:43:51 idlelands app/web.1:      at GeneratorFunctionPrototype.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:336:22) 
Sep 22 11:43:51 idlelands app/web.1:      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/app/node_modules/regenerator-runtime/runtime.js:95:21) 
Sep 22 11:43:51 idlelands app/web.1:      at step (/app/dist/plugins/pets/pet.player.giveitem.socket.js:10:183) 
Sep 22 11:43:51 idlelands app/web.1:      at /app/dist/plugins/pets/pet.player.giveitem.socket.js:10:451 
Sep 22 11:43:51 idlelands app/web.1:      at new wrappedPromise (/app/node_modules/newrelic/lib/instrumentation/core/globals.js:137:18) 
Sep 22 11:43:51 idlelands app/web.1:      at Sparky.<anonymous> (/app/dist/plugins/pets/pet.player.giveitem.socket.js:10:99) 
Sep 22 11:43:51 idlelands app/web.1:      at Sparky.petgiveitem (/app/dist/plugins/pets/pet.player.giveitem.socket.js:60:19) 
Sep 22 11:43:51 idlelands app/web.1:      at emitOne (events.js:96:13) 
Sep 22 11:43:51 idlelands app/web.1:      at Sparky.emit (events.js:188:7) 
Sep 22 11:43:51 idlelands app/web.1:      at Sparky.incoming (/app/node_modules/primus-emit/index.js:72:44) 
Sep 22 11:43:51 idlelands app/web.1:      at transform (/app/node_modules/primus/spark.js:341:33) 
Sep 22 11:43:51 idlelands app/web.1:      at Sparky.transforms (/app/node_modules/primus/spark.js:359:4) 
Sep 22 11:43:51 idlelands app/web.1:      at decoding (/app/node_modules/primus/spark.js:217:13) 
Sep 22 11:43:51 idlelands app/web.1:      at Sparky.decoder (/app/node_modules/primus/parsers/json.js:34:3) 
```

**Comment by seiyria** [comment]
wat?
```
Sep 22 11:40:15 idlelands app/web.1:  TypeError: Cannot read property '$pets' of undefined 
Sep 22 11:40:15 idlelands app/web.1:      at _callee$ (/app/dist/plugins/pets/pet.player.takeitem.socket.js:44:25) 
Sep 22 11:40:15 idlelands app/web.1:      at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:62:40) 
Sep 22 11:40:15 idlelands app/web.1:      at GeneratorFunctionPrototype.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:336:22) 
Sep 22 11:40:15 idlelands app/web.1:      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/app/node_modules/regenerator-runtime/runtime.js:95:21) 
Sep 22 11:40:15 idlelands app/web.1:      at step (/app/dist/plugins/pets/pet.player.takeitem.socket.js:10:183) 
Sep 22 11:40:15 idlelands app/web.1:      at /app/dist/plugins/pets/pet.player.takeitem.socket.js:10:451 
Sep 22 11:40:15 idlelands app/web.1:      at new wrappedPromise (/app/node_modules/newrelic/lib/instrumentation/core/globals.js:137:18) 
Sep 22 11:40:15 idlelands app/web.1:      at Sparky.<anonymous> (/app/dist/plugins/pets/pet.player.takeitem.socket.js:10:99) 
Sep 22 11:40:15 idlelands app/web.1:      at Sparky.pettakeitem (/app/dist/plugins/pets/pet.player.takeitem.socket.js:60:19) 
Sep 22 11:40:15 idlelands app/web.1:      at emitOne (events.js:96:13) 
Sep 22 11:40:15 idlelands app/web.1:      at Sparky.emit (events.js:188:7) 
Sep 22 11:40:15 idlelands app/web.1:      at Sparky.incoming (/app/node_modules/primus-emit/index.js:72:44) 
Sep 22 11:40:15 idlelands app/web.1:      at transform (/app/node_modules/primus/spark.js:341:33) 
Sep 22 11:40:15 idlelands app/web.1:      at Sparky.transforms (/app/node_modules/primus/spark.js:359:4) 
Sep 22 11:40:15 idlelands app/web.1:      at decoding (/app/node_modules/primus/spark.js:217:13) 
Sep 22 11:40:15 idlelands app/web.1:      at Sparky.decoder (/app/node_modules/primus/parsers/json.js:34:3) 
```
