### ISSUE TITLE
attack somehow does bad amounts of damage

### ISSUE THREAD

**Issue by seiyria** [IdleLands/IdleLands#635]
```
[Tue Mar 21 2017 23:14:47 GMT+0000 (UTC)] {Statistics} Someone is attempting to add a non-finite number to Combat.Receive.Damage. Fix it!
2017-03-21T18:14:47.546-05:00 at Statistics._addStat (/home/bas/app_102b7923-c4ba-4109-8024-ae115ebc2940/dist/plugins/statistics/statistics.js:44:49)
2017-03-21T18:14:47.546-05:00 at Attack.cast (/home/bas/app_102b7923-c4ba-4109-8024-ae115ebc2940/dist/plugins/combat/spell.js:77:11)
2017-03-21T18:14:47.546-05:00 at Function.forEach (/home/bas/app_102b7923-c4ba-4109-8024-ae115ebc2940/node_modules/lodash/lodash.js:9359:14)
2017-03-21T18:14:47.546-05:00 at arrayEach (/home/bas/app_102b7923-c4ba-4109-8024-ae115ebc2940/node_modules/lodash/lodash.js:537:11)
2017-03-21T18:14:47.546-05:00 at _.each.target (/home/bas/app_102b7923-c4ba-4109-8024-ae115ebc2940/dist/plugins/combat/spell.js:83:31)
2017-03-21T18:14:47.546-05:00 at Attack.dealDamage (/home/bas/app_102b7923-c4ba-4109-8024-ae115ebc2940/dist/plugins/combat/spell.js:107:36)
2017-03-21T18:14:47.546-05:00 at Battle.dealDamage (/home/bas/app_102b7923-c4ba-4109-8024-ae115ebc2940/dist/plugins/combat/battle.js:255:18)
2017-03-21T18:14:47.546-05:00 at Battle.tryIncrement (/home/bas/app_102b7923-c4ba-4109-8024-ae115ebc2940/dist/plugins/combat/battle.js:78:23)
2017-03-21T18:14:47.546-05:00 at Statistics.incrementStat (/home/bas/app_102b7923-c4ba-4109-8024-ae115ebc2940/dist/plugins/statistics/statistics.js:66:14)
2017-03-21T18:14:47.547-05:00 at arrayEach (/home/bas/app_102b7923-c4ba-4109-8024-ae115ebc2940/node_modules/lodash/lodash.js:537:11)
2017-03-21T18:14:47.547-05:00 at _.each.target (/home/bas/app_102b7923-c4ba-4109-8024-ae115ebc2940/dist/plugins/combat/spells/Attack.js:71:19)
2017-03-21T18:14:47.547-05:00 at _.each.p (/home/bas/app_102b7923-c4ba-4109-8024-ae115ebc2940/dist/plugins/combat/battle.js:112:42)
2017-03-21T18:14:47.547-05:00 at Battle.takeTurn (/home/bas/app_102b7923-c4ba-4109-8024-ae115ebc2940/dist/plugins/combat/battle.js:122:18)
2017-03-21T18:14:47.547-05:00 at Battle.doAttack (/home/bas/app_102b7923-c4ba-4109-8024-ae115ebc2940/dist/plugins/combat/battle.js:148:18)
2017-03-21T18:14:47.547-05:00 at Attack.preCast (/home/bas/app_102b7923-c4ba-4109-8024-ae115ebc2940/dist/plugins/combat/spells/Attack.js:25:11)
2017-03-21T18:14:47.547-05:00 at Function.forEach (/home/bas/app_102b7923-c4ba-4109-8024-ae115ebc2940/node_modules/lodash/lodash.js:9359:14)
```

2k ilp bounty

**Comment by seiyria** [comment]
foodfight can do this too

**Comment by seiyria** [comment]
likely the same person breaking stuff
